// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentsBE.Context;

#nullable disable

namespace StudentsBE.Migrations
{
    [DbContext(typeof(ContextDB))]
    [Migration("20230302175054_AgreeHabilitiesConfiguration3")]
    partial class AgreeHabilitiesConfiguration3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentsBE.Models.Hability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.ToTable("Hability", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Out loud reading",
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Reading comprehension",
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Readability",
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "Coherence",
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "Sum",
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 6,
                            Name = "Subtraction",
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 7,
                            Name = "Multiplication",
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 8,
                            Name = "Division",
                            SubjectId = 2
                        });
                });

            modelBuilder.Entity("StudentsBE.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Student", (string)null);
                });

            modelBuilder.Entity("StudentsBE.Models.StudentSubjectHability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HabilityId")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HabilityId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentSubjectHability", (string)null);
                });

            modelBuilder.Entity("StudentsBE.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Subject", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Spanish"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Math"
                        });
                });

            modelBuilder.Entity("StudentsBE.Models.Hability", b =>
                {
                    b.HasOne("StudentsBE.Models.Subject", "Subject")
                        .WithMany("Habilities")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("StudentsBE.Models.StudentSubjectHability", b =>
                {
                    b.HasOne("StudentsBE.Models.Hability", "Hability")
                        .WithMany("StudentSubjectHabilities")
                        .HasForeignKey("HabilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentsBE.Models.Student", "Student")
                        .WithMany("StudentSubjectHabilities")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hability");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentsBE.Models.Hability", b =>
                {
                    b.Navigation("StudentSubjectHabilities");
                });

            modelBuilder.Entity("StudentsBE.Models.Student", b =>
                {
                    b.Navigation("StudentSubjectHabilities");
                });

            modelBuilder.Entity("StudentsBE.Models.Subject", b =>
                {
                    b.Navigation("Habilities");
                });
#pragma warning restore 612, 618
        }
    }
}
